### ISSUE TITLE
Discrepancy between coordinate for moving object and coordinate for creating polygons

### ISSUE THREAD

**Issue by lucamug** [evancz/elm-playground#14]
The function that moves object use a coordinate system where positive numbers goes in the top-right direction.

The function that creates polygons use the original SVG coordinate system where positive numbers goes in the bottom-right direction.

One of these two system should be inverted.

Example to invert the polygon y axis:

from

```
addPoint : ( Float, Float ) -> String -> String
addPoint ( x, y ) str =
    str ++ String.fromFloat x ++ "," ++ String.fromFloat y ++ " "
```

to

```
addPoint : ( Float, Float ) -> String -> String
addPoint ( x, y ) str =
    str ++ String.fromFloat x ++ "," ++ String.fromFloat -y ++ " "
```

**Comment by evancz** [comment]
Should be fixed by #15. Thank you for the report and fix!

(Also, I ran into your 3D version of the playground and I think it's really cool! That was what I wanted to make next once Ian's elm-3d-scene comes out. Separately, I have a bunch of ideas of what to do next with this library. E.g. making a `playground.elm-lang.org` with examples for people to browse through. Please message me on Slack if you are interested in working something like that as well!)
