### ISSUE TITLE
Package can't be installed

### ISSUE THREAD

**Issue by dan-mcdonald** [evancz/elm-playground#2]
Running elm 0.19.0 on Windows 10. I created a new project with `elm init` and tried to install this package.

```
> elm install evancz/elm-playground
-- PACKAGE NOT FOUND -----------------------------------------------------------

I cannot find a evancz/elm-playground package on the package website.

Maybe you want one of these instead?

    evancz/elm-markdown
    jcollard/elm-playground
    evancz/elm-graphics
    evancz/elm-svg

But check <https://package.elm-lang.org> to see all possibilities!
```

**Comment by MartinSStewart** [comment]
Probably a related issue: I tried adding `evancz/elm-playground` to an ellie app.  After doing so I can no longer compile the app. The `Compiling...` animation just continues forever.

**Comment by evancz** [comment]
I noticed the same thing. I just released a 1.0.1 update with some fixes, which I think will correct the problem. If not, I know that removing `~/.elm` fixed it on my machine.

Please let me know if either of those fix it! And if so, which one!

**Comment by dan-mcdonald** [comment]
@evancz This morning I tried manually updating my `elm.json` file and running `elm make` which complained about a corrupt cache directory and said maybe I should delete it. I did that and was able to install version `1.0.0`. Anyway seems fixed now and probably not even related to this package so feel free to close this issue.

**Comment by evancz** [comment]
I swapped out GitHub API keys yesterday on the package website, so my feeling is that this caused some temporary problem with calls like https://package.elm-lang.org/all-packages/since/8940 leading to some `~/.elm` directories to be missing some number of entries. Everything looks like it is in order with the static assets from that time, so it's hard to know what kind of remediation is possible or what exactly was going wrong.

I know `rm -r ~/.elm` can fix it, but I'm not sure how many packages were published in the time window where the API key was swapped.

Point is, the root problem is definitely somewhere else, but this report starts to show which packages were in that window!
